### ISSUE TITLE
Yeni Ev'de düzenle deyince ana sayfaya gitmeden? düzenlendiğine dair bir mesaj verelim

### ISSUE THREAD

**Issue by morkedi** [chakian/HomeInventoryWeb#14]
Ne bilim yeşil bir tick, bir done yazısı o tip minik bir işaret:)

**Comment by chakian** [comment]
Düzenle dendiğinde Evler listesine geri dönecek değişikliği test ortamına attım. Diğer eklemeleri de yapıp haber veririm.
