### ISSUE TITLE
Alt kategoriye bir alt kategori ekleyince hata alıyoruz.

### ISSUE THREAD

**Issue by morkedi** [chakian/HomeInventoryWeb#17]
![image](https://user-images.githubusercontent.com/73840012/170570771-de1db550-5b96-4ae6-bde2-cb6e4d3ce57f.png)

**Comment by chakian** [comment]
Test ortamına deploy ettim.

https://stoktest.chakian.com

**Comment by morkedi** [comment]
teşekkürler, eline sağlık, test edince yazarım

**Comment by morkedi** [comment]
Var olan bir kategoriye tıklayıp, giriş yapamıyorum test ortamında, müsait olunca bakabilir misin @chakian

**Comment by chakian** [comment]
related issue #13
